conformerwrapper:
    codebook_size: 1024
    num_quantizers: 8
    conformer:
        dim: 1024
        depth: 12
        heads: 8
        dim_head: 128
        attn_flash: false

soundstorm:
    num_semantic_token_ids: 1024
    semantic_pad_id: 1024
    pad_id: 1024
    schedule: 'cosine'

stylemodule:
    bert_name: 'bert-base-multilingual-cased'
    output_dim: 1024
    prompt_seq_len: 
    mert_seq_len:
    dim_head: 128
    heads: 8
    depth: 6
    device: 'cuda'
    timesteps: 1000
    causal: false
    use_ddim: true
    noise_schedule: 'sigmoid'
    objective: 'v'

kmeans: 
    path: 

dataprocessor:
    sr: 24000
    channels: 1
    batch_size: 8
    num_workers: 1
    dataset_dir:
    train_test_split: 0.9
    min_duration: 30
    max_duration: 90
    num_buckets: 10
    sample_length: 240000
    aug_shift: true
    cache_dir: 
    labels: true
    device: 'cuda'
    n_tokens: 
    train_semantic: false

trainer:
    num_warmup_steps: 4000
    batch_size: 8
    epochs: 50
    lr: 6e-4
    initial_lr: 3e-5
    grad_accum_every: 2
    log_steps: 10
    save_model_steps: 5000
    results_folder:
    log_dir:
    accelerate_kwargs:
       log_with: 'tensorboard'
       project_dir:
    num_ckpt_keep:
    use_tensorboard:
    loss_weight: [1, 1]